blog/urls.py
from django.conf.urls import url
from views import *

urlpatterns = [
    url(r'^$', post_list, name='post_list'),
    url(r'^(?P<year>\d{4})/(?P<month>\d{2})/(?P<day>\d{2})/(?P<post>[-\w]+)/$',
        post_detail, name='post_detail'),
    url(r'^(?P<post_id>\d+)/share/$', post_share, name='post_share'),
    url(r'^tag/(?P<tag_slug>[-\w]+)/$', post_list, name='post_list_by_tag'),
]

mysite/urls.py
from django.conf.urls import include, url
from django.contrib import admin
import blog.urls

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^blog/', include('blog.urls', namespace='blog', app_name='blog')),
    #url(r'^$', include(blog.urls, namespace='blog', app_name='blog')),
]

blog/models.py
# -*- coding: utf-8 -*-
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.core.urlresolvers import reverse
from taggit.managers import TaggableManager
#from django.utils.encoding import python_2_unicode_compatible
# Create your models here.

# class PublishedManager(models.Manager):
#     def get_queryset(self):
#         return super(PublishedManager, self).get_queryset().filter(status='published')
#
# class DraftedManager(models.Manager):
#     def get_queryset(self):
#         return super(DraftedManager, self).get_queryset().filter(status='draft')

#@python_2_unicode_compatible  #为了解决中文无法添加的问题  在settings中设置
class Post(models.Model):
    STATUS_CHOICES = (
        ('draft', 'Draft'),
        ('published', 'Published'),
    )
    title = models.CharField(max_length=250)
    slug = models.SlugField(max_length=250, unique_for_date='publish') #for URLs
    author = models.ForeignKey(User, related_name='blog_posts')
    body = models.TextField()
    publish = models.DateTimeField(default=timezone.now)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    status = models.CharField(max_length=10, choices=STATUS_CHOICES, default='draft')
    tags = TaggableManager()
    #published = PublishedManager()      #如果加上此行，admin无法显示 draft类型的内容
    #drafted = DraftedManager()

    def get_absolute_url(self):
        #根据提供的试图和参数的值来逆向查找URLconf，匹配相应的url然后把值拿回来
        return reverse('blog:post_detail',
                       args=[self.publish.year,
                             self.publish.strftime('%m'),
                             self.publish.strftime('%d'),
                             self.slug])

    class Mate:
        ordering = ('-publish',)
    def __str__(self):
        return self.title

class Comment(models.Model):
    post = models.ForeignKey(Post, related_name="comments") #可以使用post.comments来访问comment中的内容
    name = models.CharField(max_length=80)
    email = models.EmailField()
    body = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    active = models.BooleanField(default=True)

    class Meta:
        ordering = ('created',)
    def __str__(self):
        return 'Comment by {} on {}'.format(self.name, self.post)

blog/forms.py
# -*- coding: utf-8 -*-
from django import forms
from models import Comment



class EmailPostForm(forms.Form):
    name = forms.CharField(max_length=25)  #默认的 HTML 代码为 <input type="text">
    email = forms.EmailField()
    to = forms.EmailField()
    comments = forms.CharField(required=False, widget=forms.Textarea) #每一个field都有一个默认的widget，可以使用widget重新定义

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('name','email', 'body')

blog/views.py
# -*- coding: utf-8 -*-
from django.shortcuts import render, get_object_or_404
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from models import Post, Comment
from forms import EmailPostForm, CommentForm
from django.core.mail import send_mail
from django.http import HttpResponseRedirect
from taggit.models import Tag
from django.db.models import Count

# import sys
# reload(sys)
# sys.setdefaultencoding("utf8")      #解决中文编码问题 python2.7以后setdefaultencoding就废弃掉了，所以在python3.x中不可使用

# Create your views here.

def post_list(request, tag_slug=None):
    #posts = Post.published.all()
    object_list = Post.objects.filter(status='published')

    tag = None
    if tag_slug:
        tag = get_object_or_404(Tag, slug=tag_slug)
        object_list = object_list.filter(tags__in=[tag])  #tags__in 需要注意


    paginator = Paginator(object_list, 3)       #分页
    page = request.GET.get('page')
    try:
        posts = paginator.page(page)
    except PageNotAnInteger:
        posts = paginator.page(1)  # 如果page不是一个整数，则返回第一页
    except EmptyPage:
        posts = paginator.page(paginator.num_pages) #如果page不在范围之内，则返回最后一个 page
    return render(request, 'blog/post/list.html',
                  {'page':page, 'posts':posts, 'tag':tag})

def post_detail(request, year, month, day, post):
    post = get_object_or_404(Post, slug=post,
                             status='published',
                             publish__year=year,
                             publish__month=month,
                             publish__day=day)
    comments = post.comments.filter(active=True)
    comments_flag = False
    if request.method == 'POST':
        #a comment was posted
        comment_form = CommentForm(data=request.POST)
        if comment_form.is_valid():
            #Create Comment object but don't save to database yet
            new_comment = comment_form.save(commit=False)
            #Assign the current post to the comment
            new_comment.post = post
            #Save the comment to the database
            new_comment.save()
            comments_flag = True
            #防止刷新网页是重复提交表单
            return HttpResponseRedirect(request.get_full_path())
    else:
        comment_form = CommentForm()

    post_tags_ids = post.tags.values_list('id', flat=True)
    similar_posts = Post.objects.filter(status='published').filter(tags__in=post_tags_ids).exclude(id=post.id)
    similar_posts = similar_posts.annotate(same_tags=Count('tags')).order_by('-same_tags', '-publish')[:4]
    #print 'similar_posts', similar_posts

    return render(request, 'blog/post/detail.html',
                  {'post':post,
                   'comments': comments,
                   'comment_form':comment_form,
                   'new_comment':comments_flag,
                   'similar_posts':similar_posts})

def post_share(request, post_id):
    post = get_object_or_404(Post, id=post_id, status='published')
    sent = False

    if request.method == 'POST':
        form = EmailPostForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            print 'send mail', cd, post.title
            post_url = request.build_absolute_uri(
                post.get_absolute_url()
            )   #build a complete URL including HTTP schema and hostname
            subject = '{} ({}) recommends you reading "{}"'.format(
                cd['name'], cd['email'], post.title
            )
            message = 'Read "{}" at {} \n\n {}\'s comments: {} '.format(
                post.title, post_url, cd['name'], cd['comments']
            )
            try:
                send_mail(subject, message, 'ngnetboy@163.com', [cd['to']])
            except Exception, e:
                sent = False
            sent = True
    else:
        form = EmailPostForm()

    return render(request, 'blog/post/share.html',
                  {'post':post, 'form': form, 'sent': sent})

blog/templates/blog/base.html
{% load staticfiles %}
{% load blog_tags %}
<!DOCTYPE html>
<html>
<head>
    <title>{% block title %} {% endblock %}</title>
</head>
<body>
    <div id="content">
        {% block content %}
        {% endblock %}
    </div>
    <div id="sidebar">
        <h2>My Blog</h2>
            <p>This is my blog. I've written {% total_posts %} posts so far.</p>
        <h3>Latest posts</h3>
        {% show_latest_posts 3 %}
        <h3>Most commented posts</h3>
        {% get_most_commented_posts as most_commented_posts %}
        <ul>
            {% for post in most_commented_posts %}
                <li>
                    <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
                </li>
            {% endfor %}
        </ul>
    </div>
</body>
</html>

blog/templates/blog/post/detail.html
{% extends "blog/base.html" %}
{% load blog_tags %}
{% block title %} {{ post.title }} {% endblock %}

{% block content %}
    <h1>{{ post.title }}</h1>
    <p class="date">
        Published {{ post.publish }} by {{ post.author }}
    </p>
    <!--linebreaks 将 post.body 中的 '\n' 代替为 <br/> 并使用 </p> 包围起来-->
    <!--{{ post.body|linebreaks }}-->
    {{ post.body | markdown }}
    <p>
        <!--{ url }动态地生成url，根据 blog:post_share name为post_share的url规则 -->
        <a href='{% url "blog:post_share" post.id %}'>
            Share the post
        </a>
    </p>

    <h2>Similar posts</h2>
    {% for post in similar_posts %}
        <p>
            <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
        </p>
    {% empty %}
        There are no similar posts yet.
    {% endfor %}

    {% with comments.count as total_comments %}
        <h2>
            {{ total_comments }} comment{{ total_comments|pluralize }}
        </h2>
    {% endwith %}
    {% for comment in comments %}
        <div class="comment">
            <p class="info">
                Comment {{ forloop.counter }} by {{ comment.name }}
                {{ comment.created }}
            </p>
            {{ comment.body|linebreaks }}
        </div>
    {% empty %}
        <p>There are no comments yes.</p>
    {% endfor %}

    {% if new_comment %}
        <h2>Your comment has been added.</h2>
    {% else %}
        <h2>Add a new comment</h2>
        <form action="." method="post">
            {{ comment_form.as_p }}
            {% csrf_token %}
            <p><input type="submit" value="Add comment"/> </p>
        </form>
    {% endif %}
{% endblock %}

blog/templates/blog/post/list.html
{% extends "blog/base.html" %}
{% load blog_tags %}
{% block title %} My Blog {% endblock %}

{% block content %}
    <h1>My Blog</h1>
    {% if tag %}
        <h2>Posts tagged with "{{ tag.name }}"</h2>
    {% endif %}

    {% for post in posts %}
        <h2>
            <a href="{{ post.get_absolute_url }}">
                {{ post.title }}
            </a>
        </h2>
        <!--<p class="tags">Tags: {{ post.tags.all|join:", " }}</p>-->
        <p class="tags">
            Tags:
            {% for tag in post.tags.all %}
                <a href='{% url "blog:post_list_by_tag" tag.slug %}'>
                    {{ tag.name }}
                </a>
                {% if not forloop.last %}, {% endif %}
            {% endfor %}
        </p>
        <p class="date">
            Published {{ post.publish }} by {{ post.author }}
        </p>
        <!--{{ post.body|truncatewords:30|linebreaks }}-->
        {{ post.body|markdown|truncatewords_html:30 }}
    {% endfor %}


    <!--把posts当做一个参数传递到 pagination.html中-->
    {% include "blog/post/pagination.html" with page=posts %}
{% endblock %}

blog/templates/blog/post/pagination.html
<div class="pagination">
    <span class="step-links">
        {% if page.has_previous %}
            <a href="?page={{ page.previous_page_number }}">Previous</a>
        {% endif %}
        <span class="current">
            Page {{ page.number }} of {{ page.paginator.num_pages }}.
        </span>
        {% if page.has_next %}
            <a href="?page={{ page.next_page_number }}">Next</a>
        {% endif %}
    </span>
</div>

blog/templates/blog/post/share.html
{% extends "blog/base.html" %}

{% block title %} Share a post {% endblock %}

{% block content %}
    {% if sent %}
        <h1>E-mail successfully sent</h1>
        <p>
            "{{ post.title }}" was successfully sent to {{ cd.to }}.
        </p>
    {% else %}
        <h1>Share "{{ post.title }}" by e-mail</h1>
        <form action="." method="post">
            {{ form.as_p }}
            {% csrf_token %}
            <input type="submit" value="Send e-mail">
        </form>
    {% endif %}

{% endblock %}